/* 自动生成 */
window.__LANG__ = {
 "zh": {
  "searchPlaceholder": "搜索...",
  "emptyTitle": "没有符合条件的图片",
  "emptyHint": "尝试清空搜索或切换筛选条件，目前仅支持搜索文件名，未做人物、事件等关键词分类。",
  "stats": "共 {total} 张 · 当前显示 {shown} 张",
  "scopeLabel": "",
  "allLabel": "全部",
  "recentLabel": "最近",
  "featuredLabel": "★ 精选",
  "yearLabel": "按年份",
  "folderLabel": "按文件夹",
  "sortLabel": "排序",
  "sortTime": "按时间",
  "sortAZ": "A-Z",
  "sortZA": "Z-A",
  "longLabel": "长图",
  "loading": "加载中...",
  "noNetwork": "设备无网络连接",
  "retry": "重试",
  "prev": "上一张 (←)",
  "next": "下一张 (→)",
  "zoomIn": "放大",
  "zoomOut": "缩小",
  "zoomReset": "适应窗口",
  "close": "关闭",
  "lang": "切换语言",
  "menu": "菜单",
  "menuRepo": "前往/返回 GitHub ",
  "menuAbout": "相关",
  "aboutTitle": "《赛博史记》",
  "aboutQ1": "这是什么？",
  "aboutA1": "衍生自 Record 的图片浏览站点，优化浏览过程。",
  "aboutQ2": "这会对我造成什么危害？",
  "aboutA2": "你完了！猫耳河豚已经盯上你了，她会趁你不备突然扎你，狠狠扎你，天天扎你！",
  "aboutQ3": "为什么这里的内容和仓库里的不一致？",
  "aboutA3": "一切皆有豚数...",
  "aboutA3b": "豚有异术：每值日曜午时，鼓腹裂波，破渊而出。自私窟潜赴公海，摄其元胚，归而炼石成阵，复推玄牝之库。周行如律，世谓“豚缸惊变”云。",
  "dataMissing": "索引数据缺失：未找到data/index.js",
  "titleSuffix": "· 图鉴"
 },
 "en": {
  "searchPlaceholder": "Search...",
  "emptyTitle": "No matching images",
  "emptyHint": "Try clearing search or changing filters. Currently only supports file name search, no keyword classification for people, events, etc.",
  "stats": "{total} images · showing {shown}",
  "scopeLabel": "",
  "allLabel": "All",
  "recentLabel": "Recent",
  "featuredLabel": "★ Featured",
  "yearLabel": "By Year",
  "folderLabel": "By Folder",
  "sortLabel": "Sort",
  "sortTime": "By Time",
  "sortAZ": "A-Z",
  "sortZA": "Z-A",
  "longLabel": "Long",
  "loading": "Loading...",
  "noNetwork": "No network connection",
  "retry": "Retry",
  "prev": "Previous (←)",
  "next": "Next (→)",
  "zoomIn": "Zoom in",
  "zoomOut": "Zoom out",
  "zoomReset": "Fit window",
  "close": "Close",
  "lang": "Switch language",
  "menu": "Menu",
  "menuRepo": "Go to / Return to GitHub",
  "menuAbout": "About",
  "aboutTitle": "Cyber Chronicle",
  "aboutQ1": "What is this?",
  "aboutA1": "A browsing site derived from Record.",
  "aboutQ2": "Will this harm me?",
  "aboutA2": "You're done for! The cat-eared pufferfish has her eyes on you. She'll poke you when you least expect it, poke you hard, poke you every day!",
  "aboutQ3": "Why is the content here different from the repository?",
  "aboutA3": "Everything has its puffer number...",
  "aboutA3b": "豚有异术：每值日曜午时，鼓腹裂波，破渊而出。自私窟潜赴公海，摄其元胚，归而炼石成阵，复推玄牝之库。周行如律，世谓“豚缸惊变”云。",
  "dataMissing": "Index data missing: data/index.js not found",
  "titleSuffix": "· Gallery"
 }
};
