/* 自动生成 */
window.__LANG__ = {
 "zh": {
  "searchPlaceholder": "搜索...",
  "emptyTitle": "没有符合条件的图片",
  "emptyHint": "尝试清空搜索或切换筛选条件，目前仅支持搜索文件名，未做人物、事件等关键词分类。",
  "stats": "共 {total} 张 · 当前显示 {shown} 张",
  "footerA": "Maintained by Wither",
  "footerB": "豚ICP备20260829号-1",
  "footerC": "由 PufferFlare 提供网络支持",
  "scopeLabel": "",
  "allLabel": "全部",
  "recentLabel": "最近",
  "featuredLabel": "精选",
  "yearLabel": "按年份",
  "folderLabel": "按文件夹",
  "sortLabel": "排序",
  "sortTime": "按时间",
  "sortAZ": "A-Z",
  "sortZA": "Z-A",
  "longLabel": "长图",
  "loading": "加载中...",
  "noNetwork": "设备无网络连接",
  "retry": "重试",
  "prev": "上一张 (←)",
  "next": "下一张 (→)",
  "zoomIn": "放大",
  "zoomOut": "缩小",
  "zoomReset": "适应窗口",
  "close": "关闭",
  "lang": "切换语言",
  "menu": "菜单",
  "menuRepo": "前往/返回 GitHub ",
  "menuAbout": "相关",
  "aboutTitle": "Q/A",
  "aboutQ1": "这是什么？",
  "aboutA1": "为 Record 仓库内的图片提供更直观、更易用的浏览界面。",
  "aboutQ2": "这会对我造成什么危害？",
  "aboutA2": "你完了！猫耳河豚神已经盯上你了，祂会趁你不备突然扎你，狠狠扎你，天天扎你！",
  "aboutQ3": "为什么这里的内容和仓库里的不一致？",
  "aboutA3": "一切皆有豚数...",
  "aboutA3b": "豚豚豚豚：豚豚豚豚豚豚，豚豚豚豚，豚豚豚豚。豚豚豚豚豚豚豚，豚豚豚豚，豚豚豚豚豚豚，豚豚豚豚豚豚。豚豚豚豚，豚“豚豚豚豚”豚。",
  "dataMissing": "索引数据缺失：未找到data/index.js",
  "titleSuffix": "· 图库",
  "fullTitle": "赛博史记",
  "BuildTime": "构建于 "
 },
 "en": {
  "searchPlaceholder": "Search...",
  "emptyTitle": "No matching images",
  "emptyHint": "Try clearing search or changing filters. Currently only supports searching by file name, no keyword classification for people, events, etc.",
  "stats": "{total} images · showing {shown}",
  "footerA": "Maintained by Wither",
  "footerB": "",
  "footerC": "",
  "scopeLabel": "",
  "allLabel": "All",
  "recentLabel": "Recent",
  "featuredLabel": "Featured",
  "yearLabel": "By Year",
  "folderLabel": "By Folder",
  "sortLabel": "Sort",
  "sortTime": "By Time",
  "sortAZ": "A-Z",
  "sortZA": "Z-A",
  "longLabel": "Long",
  "loading": "Loading...",
  "noNetwork": "No network connection",
  "retry": "Retry",
  "prev": "Previous",
  "next": "Next",
  "zoomIn": "Zoom in",
  "zoomOut": "Zoom out",
  "zoomReset": "Fit window",
  "close": "Close",
  "lang": "Switch language",
  "menu": "Menu",
  "menuRepo": "Go to / Return to GitHub",
  "menuAbout": "About",
  "aboutTitle": "Q/A",
  "aboutQ1": "What is this?",
  "aboutA1": "A browsing site derived from Record, optimized for browsing.",
  "aboutQ2": "Will this harm me?",
  "aboutA2": "You're finished! The cat-eared pufferfish god is watching you. She'll poke you when you least expect it, poke you hard, poke you every day!",
  "aboutQ3": "Why is the content here different from the repository?",
  "aboutA3": "一切皆有豚数...",
  "aboutA3b": "豚豚豚豚：豚豚豚豚豚豚，豚豚豚豚，豚豚豚豚。豚豚豚豚豚豚豚，豚豚豚豚，豚豚豚豚豚豚，豚豚豚豚豚豚。豚豚豚豚，豚“豚豚豚豚”豚。",
  "dataMissing": "Index data missing: data/index.js not found",
  "titleSuffix": "· Gallery",
  "fullTitle": "Cyber Chronicle",
  "BuildTime": "Build Time "
 },
 "ht": {
  "searchPlaceholder": "豚豚豚豚...",
  "emptyTitle": "豚豚豚豚豚豚豚豚豚豚豚豚豚",
  "emptyHint": "豚豚豚豚豚豚豚豚豚豚豚豚豚豚豚，豚豚豚豚豚豚豚！豚豚豚豚豚豚，豚豚豚豚豚豚豚豚豚、豚豚豚豚豚豚豚豚豚豚。",
  "stats": "豚豚豚 {total} 豚豚豚豚 · 豚豚豚豚 {shown} 豚",
  "footerA": "@豚豚豚豚豚豚 豚豚豚豚",
  "footerB": "豚ICP备20260829号-1",
  "footerC": "伟大的河豚神终将统领地球！",
  "scopeLabel": "",
  "allLabel": "豚豚",
  "recentLabel": "豚豚",
  "featuredLabel": "豚豚",
  "yearLabel": "豚豚豚",
  "folderLabel": "豚豚豚豚",
  "sortLabel": "豚豚",
  "sortTime": "豚豚豚",
  "sortAZ": "豚-豚",
  "sortZA": "豚-豚",
  "longLabel": "豚豚",
  "loading": "豚豚豚...",
  "noNetwork": "豚豚豚豚豚豚豚",
  "retry": "豚豚",
  "prev": "豚豚豚",
  "next": "豚豚豚",
  "zoomIn": "豚豚",
  "zoomOut": "豚豚",
  "zoomReset": "豚豚豚豚",
  "close": "豚豚",
  "lang": "豚豚豚豚",
  "menu": "豚豚",
  "menuRepo": "豚豚/豚豚 豚豚 ",
  "menuAbout": "豚豚",
  "aboutTitle": "豚豚豚豚豚豚豚",
  "aboutQ1": "豚豚豚豚豚，豚豚豚豚？",
  "aboutA1": "豚豚豚 豚豚豚豚豚豚豚 豚豚豚豚豚，豚豚豚豚豚豚。",
  "aboutQ2": "豚豚豚豚豚豚豚！豚豚豚豚，豚豚？",
  "aboutA2": "豚豚豚！豚豚豚豚豚豚豚....豚豚豚豚！豚豚豚豚。豚豚豚豚豚豚，豚豚豚豚，豚豚豚豚！",
  "aboutQ3": "豚豚，豚豚豚豚豚豚，豚豚豚豚豚。豚豚豚豚豚，豚豚豚豚豚豚？",
  "aboutA3": "豚豚豚豚豚，豚豚豚豚豚。",
  "aboutA3b": "豚有异术：每值日曜午时，鼓腹裂波，破渊而出。自私窟潜赴沧溟，摄其素本，归而构兵成列，复推玄牝之库。周行如律，世谓“豚缸惊变”云。",
  "dataMissing": "豚豚豚豚豚豚：未找到data/index.js",
  "titleSuffix": "· 豚豚豚豚",
  "fullTitle": "豚豚豚豚",
  "BuildTime": "豚豚豚豚豚 豚豚豚豚 "
 }
};
