/* 自动生成 */
window.__LANG__ = {
 "zh": {
  "searchPlaceholder": "搜索名称、标签、人物…",
  "emptyTitle": "没有符合条件的图片",
  "emptyHint": "试试清空搜索或切换筛选条件",
  "stats": "共 {total} 张 · 显示 {shown} 张",
  "scopeLabel": "范围",
  "allLabel": "全部",
  "featuredLabel": "★ 精选",
  "yearLabel": "年份",
  "folderLabel": "文件夹",
  "sortLabel": "排序",
  "sortTime": "时间",
  "sortAZ": "A-Z",
  "sortZA": "Z-A",
  "longLabel": "长图",
  "loading": "加载中...",
  "loadFailed": "加载失败...",
  "noNetwork": "无网络连接",
  "retry": "重试",
  "prev": "上一张 (←)",
  "next": "下一张 (→)",
  "zoomIn": "放大",
  "zoomOut": "缩小",
  "zoomReset": "适应窗口",
  "close": "关闭 (Esc)",
  "lang": "切换语言",
  "dataMissing": "索引数据加载失败：未找到 data/index.js",
  "titleSuffix": "· 图鉴"
 },
 "en": {
  "searchPlaceholder": "Search name, tags, people…",
  "emptyTitle": "No matching images",
  "emptyHint": "Try clearing search or filters",
  "stats": "{total} images · showing {shown}",
  "scopeLabel": "Scope",
  "allLabel": "All",
  "featuredLabel": "★ Featured",
  "yearLabel": "Year",
  "folderLabel": "Folder",
  "sortLabel": "Sort",
  "sortTime": "Time",
  "sortAZ": "A-Z",
  "sortZA": "Z-A",
  "longLabel": "Long",
  "loading": "Loading...",
  "loadFailed": "Load failed...",
  "noNetwork": "No network connection",
  "retry": "Retry",
  "prev": "Previous (←)",
  "next": "Next (→)",
  "zoomIn": "Zoom in",
  "zoomOut": "Zoom out",
  "zoomReset": "Fit window",
  "close": "Close (Esc)",
  "lang": "Switch language",
  "dataMissing": "Index data missing: data/index.js not found",
  "titleSuffix": "· Gallery"
 }
};
